# Generated by Django 2.2.6 on 2019-11-09 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinefilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('run', models.CharField(max_length=10)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('vivienda', models.CharField(choices=[('Casa con patio grande', 'Casa con patio grande'), ('Casa con patio pequeño', 'Casa con patio pequeño'), ('Casa sin patio', 'Casa sin patio'), ('Departamento', 'Departamento')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('anio', models.IntegerField(verbose_name='año')),
                ('duracion', models.IntegerField()),
                ('pais', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('fecha_estreno', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('cinefilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cinefilo')),
            ],
        ),
    ]
