# Generated by Django 2.2.6 on 2019-11-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191111_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='cinefilo',
            new_name='user',
        ),
    ]
