# Generated by Django 2.2.6 on 2019-11-12 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20191111_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=12)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('vivienda', models.CharField(choices=[('Casa con patio grande', 'Casa con patio grande'), ('Casa con patio pequeño', 'Casa con patio pequeño'), ('Casa sin patio', 'Casa sin patio'), ('Departamento', 'Departamento')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cinefilo',
        ),
    ]
