# Generated by Django 2.2.6 on 2019-11-14 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191112_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='fecha_estreno',
        ),
    ]
