# Generated by Django 3.1.4 on 2020-12-04 00:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20201203_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pelicula',
            new_name='Libro',
        ),
    ]
